NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 999
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 999
NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 30
NDefines.NCountry.EVENT_PROCESS_OFFSET = 25
NDefines.NGame.GAME_SPEED_SECONDS = { 0.4, 0.2, 0.1, 0.07, 0.0 }

NDefines.NCountry.POPULATION_YEARLY_GROWTH_BASE = 0.0

NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 999
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 999
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 999

NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 0 	
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 0	
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 0 	

NDefines.NMilitary.LAND_EQUIPMENT_BASE_COST = 1				
NDefines.NMilitary.LAND_EQUIPMENT_RAMP_COST = 0					
NDefines.NMilitary.NAVAL_EQUIPMENT_BASE_COST = 1
NDefines.NMilitary.NAVAL_EQUIPMENT_RAMP_COST = 0
NDefines.NMilitary.AIR_EQUIPMENT_BASE_COST = 1
NDefines.NMilitary.AIR_EQUIPMENT_RAMP_COST = 0

NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST = 0.0			
NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 0.0				
NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST = 0.0			
NDefines.NProduction.EQUIPMENT_MODULE_REMOVE_XP_COST = 0.0

NDefines.NMilitary.LAND_AIR_COMBAT_MAX_PLANES_PER_ENEMY_WIDTH = 0.5
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 30

NDefines.NMilitary.MIN_DIVISION_BRIGADE_HEIGHT = 5

NDefines.NAI.JOIN_ALLY_BASE_DESIRE = -500					
NDefines.NAI.JOIN_ALLY_DEMOCRATIC_DESIRE = 0		
NDefines.NAI.JOIN_ALLY_NEUTRAL_DESIRE = 0		
NDefines.NAI.JOIN_ALLY_FASCIST_DESIRE = 0			
NDefines.NAI.JOIN_ALLY_COMMUNIST_DESIRE = 0			

NDefines.NOperatives.INTEL_NETWORK_MIN_VP_TO_TARGET = 5
NDefines.NOperatives.OPERATIVE_BASE_PROPAGANDA_POWER = 0
NDefines.NOperatives.OPERATIVE_BASE_BOOST_IDEOLOGY = 0
NDefines.NOperatives.PROPAGANDA_SUB_NETWORK_STRENGTH_FACTOR = 0
NDefines.NOperatives.PROPAGANDA_OPERATIVE_STACKING_FACTOR = 0
NDefines.NOperatives.PROPAGANDA_DEFENSE_FACTOR = 0
NDefines.NOperatives.PROPAGANDA_COUNTRY_STACKING_FACTOR = 0
NDefines.NOperatives.OPERATIVE_BASE_CONTROL_TRADE_DRIFT = 0
NDefines.NOperatives.CONTROL_TRADE_STACKING_FACTOR = 0
NDefines.NOperatives.CONTROL_TRADE_MAX_INFLUENCE = 0
NDefines.NOperatives.CONTROL_TRADE_INFLUENCE_DAILY_DECAY = 0
NDefines.NOperatives.MIN_NATIONAL_COVERAGE_FOR_BOOST_IDEOLOGY = 99
NDefines.NOperatives.MIN_NATIONAL_COVERAGE_FOR_PROPAGANDA = 99

NDefines.NOperatives.AGENCY_CREATION_FACTORIES = 0

NDefines.NIntel.ARMY_INTEL_COMBAT_BONUS_MAX_BONUS = 0

NDefines.NIndustrialOrganisation.DESIGN_TEAM_CHANGE_XP_COST = 1	